### ISSUE TITLE
Unable to connect- GCP Tesla T4

### ISSUE THREAD

**Issue by djraval** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#1]
Upon successful execution of the script and verifying everything is installed, I still get the "We couldn't initialize the hosting functionality".

I have 
- tried both x265 and x264 on the hosting settings
- Selected the display adapter for T4
- Checked the firewall rules
- verified driver installetion status

Using another GPU isn't an option as only T4 is available in my region.
Searched but could not find any related logs, if possible direct me me I can post the logs related to it here on this thread.

**Comment by djraval** [comment]
Apparently,
It seems RDP session is causing the issue.
Once I disconnect from RDP and Reboot the system I can easily connect to the remote machine.

Surely some kind of bug but this is a workaround.

**Comment by jamesstringerparsec** [comment]
This isn't a bug, connecting via Parsec and RDP is not supported as RDP creates a virtual desktop session, which Parsec cannot capture.
