### ISSUE TITLE
PostInstall.ps1 has a TLS security error

### ISSUE THREAD

**Issue by steventhegeek** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#14]
In line 489, the call to download ParsecServiceManager.exe fails, I assume with a security error.
Inserting [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls" before it seems to fix it.

**Comment by jamesstringerparsec** [comment]
What cloud platform did you experience this on?

**Comment by steventhegeek** [comment]
AWS, stock server 2016 base image on g4dn.2xlarge. With the single line
added, I  just reran it and it completed like butter.
I believe I got it on an Azure Windows 10 Machine though last night too but
wouldn't bet my life on it.
