### ISSUE TITLE
Setup Auto Shutdown Crashes Second Time

### ISSUE THREAD

**Issue by oloflarsson** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#17]
**In Short**
The "Setup Auto Shutdown" worked well the first time, but on second time usage it crashes.

**Screenshot**
<img width="1581" alt="Screenshot 2020-02-19 at 18 19 03" src="https://user-images.githubusercontent.com/421009/74857698-5d837800-5344-11ea-9b37-ca85975c8a61.png">

**Comment by jamesstringerparsec** [comment]
OK, it's complaining the file already exists, I just need to change the script to check if the item exists and replace if so.

**Comment by jamesstringerparsec** [comment]
Fixed

**Comment by oloflarsson** [comment]
Awesome! Good job 👍!
