### ISSUE TITLE
no 'setup auto login' on desktop instead 'auto login' empty folder?

### ISSUE THREAD

**Issue by nikolarobottesla** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#19]
![image](https://user-images.githubusercontent.com/13294739/75637599-8d106b00-5bf5-11ea-87a0-33ca825db812.png)

paperspace P4000, 250GB SSD, windows server 2019

**Comment by nikolarobottesla** [comment]
Is the 'setup auto login' text file still a thing?

**Comment by jamesstringerparsec** [comment]
Not required on Paperspace, that's why it's empty
