### ISSUE TITLE
Parsec Service Manager install broken - dead link

### ISSUE THREAD

**Issue by joeraut** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#21]
The URL to download ParsecServiceManager.exe, https://github.com/jamesstringerparsec/Parsec-Service-Manager/raw/master/ParsecServiceManager.exe, returns a 404 due to the file being renamed in the [Parsec-Service-Manager repository](https://github.com/jamesstringerparsec/Parsec-Service-Manager/).

PowerShell returns the following error when running the preparation tool:
```
Creating Parsec Service
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: The connection was closed
unexpectedly."
At C:\Users\Administrator\Desktop\parsectemp\PostInstall\PostInstall.ps1:490 char:1
+ (New-Object System.Net.WebClient).DownloadFile("https://github.com/ja ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

**Comment by joeraut** [comment]
Pushed pull request #22 with fix.

**Comment by jamesstringerparsec** [comment]
I updated the link, thanks for the reminder!
