### ISSUE TITLE
Azure NVv4 VM Support

### ISSUE THREAD

**Issue by cktechative** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#23]
Would it be possible to add Azure NVv4 VM Support?
https://docs.microsoft.com/en-us/azure/virtual-machines/nvv4-series
Best Regards
Christian

**Comment by jamesstringerparsec** [comment]
You can test it yourself...do everything except GPU updater.  Then install the AMD driver.  I don't think it will work though since they advertise it as a compute card, not a graphics card.

**Comment by cktechative** [comment]
Yes i did previously, it did not work. Maybe the encoder works only on nvidia based cards...
