### ISSUE TITLE
Can't install Origin

### ISSUE THREAD

**Issue by Sam-Kruglov** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#27]
Just letting you know that this tool should probably install [both x86 and x64 Visual C++](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) packages. 
I wasn't able to install Origin until I installed the x86 package.

[similar](https://answers.ea.com/t5/Origin-Client-Web-Technical/missing-VCRUNTIME140-dll-and-MSVCP140-dll-Origin-wont-open/td-p/6415724)

**Comment by steventhegeek** [comment]
Isn’t that origins job to check? I mean what if epic puts in 64bit runtime because that what it needs then origin comes along, origin should put in the x86 if it needs it.

**Comment by Sam-Kruglov** [comment]
Well, it just throws a windows error of a missing dll when you try to launch the origin installer executable.

**Comment by voronoipotato** [comment]
either way thanks @Sam-Kruglov for documenting this. It'd be cool if you came up with an Apex legends powershell script to install dependencies and start the origin installer :). Share here if you do because I'd love to use it.

**Comment by Sam-Kruglov** [comment]
@voronoipotato you can just install them manually from the link above. I don't think I will make a script
