### ISSUE TITLE
Parsec Service Manager fails to download

### ISSUE THREAD

**Issue by Shakahs** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#28]
https://github.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool/blob/c66a64d6fac14273dfc76aff9fb52304726846f4/PostInstall/PostInstall.ps1#L490

The URL and GitHub Repo referenced in PostInstall.ps1 do not exist anymore.

**Comment by jamesstringerparsec** [comment]
It's not required anymore, I need to strip it out of the script

**Comment by jamesstringerparsec** [comment]
It's now gone.
