### ISSUE TITLE
Microsoft Xbox 360 Accessories install errors out with "Setup cannot continue because this software is not compatible with Microsoft Virtual PC"

### ISSUE THREAD

**Issue by jfly** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#29]
First off, thanks for this wonderful tool! I used it to spin up a server on Azure a few weeks ago, and it has been working great.

I was just tried to get controller support working, and have been running into a lot of trouble. I'm confident that my Parsec client has everything set up correctly, but I am pretty sure that my Parsec host (on Azure) does *not*. My understanding is that Parsec relies upon the ViGEm driver to emulate a controller, so I did try to install ViGEmBus from https://github.com/ViGEm/ViGEmBus and then reboot the host, which did not help. I then saw https://github.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool/commit/bff8a904952def036e40d2b1e6d0f7d44ffd3433, and decided to try downloading and installing `Xbox360_64Eng.exe`. When I try to run it, it errors out with "Setup cannot continue because this software is not compatible with Microsoft Virtual PC":

![image](https://user-images.githubusercontent.com/277474/79297319-a5c99d00-7e92-11ea-9072-a78531ed3a9a.png)

Any idea why this is and what the fix might be? Thanks!

**Comment by jamesstringerparsec** [comment]
What OS are you trying to install it on?
My scripts only attempt to install in on Server 2019.  I have not tested trying to install it on another OS because it was not required.

**Comment by jfly** [comment]
Oh sorry, I forgot to say that I *am* using "Windows Server 2019 Datacenter". Proof:
![2020-04-15_03-10-18_dalinar](https://user-images.githubusercontent.com/277474/79325827-b3007f00-7ec6-11ea-960c-cea8bf64463f.gif)

**Comment by jamesstringerparsec** [comment]
I have no clue, this isn't an issue with AWS and GCP in my experience.  I guess those platforms hide virtualization status.  You could see if it's down to the generation 1 vs 2 Azure VM types.  That's just a guess though.

**Comment by bfdonny** [comment]
Exact same problem here. I'm running on an Azure NV6 VM. Parsec can connect, but the controller input doesn't work. No device appears in Device Manager and html5gamepad.com obviously doesn't see a controller, either. I'm also using Windows Server 2019 datacenter. I got the same error as jfly when trying to install the 360 accessories, so I tried to install the XB1 accessories instead which didn't give any errors. I rebooted and ran the ViGEmBus installer and rebooted again and it still doesn't work. Any ideas on where to go from here?

Also, I echo jfly's thanks for putting this together. Super awesome.

**Comment by jamesstringerparsec** [comment]
Are you running generation 2 or generation 1 VM type..

**Comment by bfdonny** [comment]
Gen1. IIRC, the GPU instances weren't available in Gen2. Think that's the problem?

**Comment by jamesstringerparsec** [comment]
The only solution for you now is to use Server 2016.

**Comment by bfdonny** [comment]
Cool. I'll redo this with Server 2016 and report back. Thanks for the help!

**Comment by jfly** [comment]
For the record, I switched to Server 2016, and things are working great!

The perfectionist in me would still like to find a workaround for Server 2019, or at least update the scripts here to identify/warn users about this issue so they aren't left super confused as I (and @bfdonny were). I still have the Server 2019 VM floating around, I'll play around with it some more and possibly send in a PR sometime.

**Comment by jamesstringerparsec** [comment]
There is probably some Windows update from Update Catalog or Windows feature that can be installed to the VM to make the controllers work but I haven't looked into it, it's a little odd that Microsoft chose to take out whatever made controllers work by default in Server 2016 from Server 2019 but the world is an odd place.

**Comment by bfdonny** [comment]
I built a new Azure NV6 VM with Windows Server 2016 and when I try to install the Xbox 360 Accessories I'm still encountering the "Setup cannot continue because this software is not compatible with Microsoft Virtual PC" error. Any ideas?

**Comment by jamesstringerparsec** [comment]
@bfdonny You don't need the software on Server 2016, it shouldn't request install using this script.

**Comment by bfdonny** [comment]
Then maybe I'm missing something. The controller works on my local PC (as tested at html5gamepad.com) but isn't detected on the 2016 VM. I'll go through the controller troubleshooting steps again.

**Comment by jamesstringerparsec** [comment]
You can extract the .exe using 7zip and manually update the driver by selecting Virtual Xbox 360 Controller in Device Manager and manually updating the driver... look in `\Xbox360_64Eng\xbox360\setup64\files\driver\win7` with "Xbox360_64Eng" Being the folder that contains the extracted archive.

**Comment by jamesstringerparsec** [comment]
I've added the Xbox 360 Controller driver to Windows, it *Should* automatically install when you plug it in, but there is a chance that you may need to click "update drivers -> search automatically" in device manager on the "Virtual Xbox 360 Controller" if it appears in Unknown devices

**Comment by jamesstringerparsec** [comment]
This is the Powershell command to add the driver if you want to add it without re-running the entire script
```  
    (New-Object System.Net.WebClient).DownloadFile("http://download.microsoft.com/download/6/9/4/69446ACF-E625-4CCF-8F56-58B589934CD3/Xbox360_64Eng.exe","C:\ParsecTemp\Drivers\Xbox360_64Eng.exe")  
    cmd.exe /c '"C:\Program Files\7-Zip\7z.exe" x C:\ParsecTemp\Drivers\Xbox360_64Eng.exe -oC:\ParsecTemp\Drivers\Xbox360_64Eng -y' | Out-Null  
    cmd.exe /c '"C:\Program Files\Parsec\vigem\10\x64\devcon.exe" dp_add "C:\ParsecTemp\Drivers\Xbox360_64Eng\xbox360\setup64\files\driver\win7\xusb21.inf"'  
```
