### ISSUE TITLE
Virtual Server on IBM Cloud doesn't boot any more after install

### ISSUE THREAD

**Issue by bn326160** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#30]
On IBM Cloud I was able to get the System partially working using a YouTube tutorial, but was stuck on 1280x1024 resolution, so started a new instance and gave this script a try.

On both Windows Server 2016, as well as Windows Server 2019 I have this issue after I ran the script for installation, drivers and autologin, the server is unreachable. It doesn't show up on Parsec, can't connect to it over VNC, can't RDP any more and can't even ping it. Rebooting it in the cloud console doesn't help either.

Any advice on how to approach this issue? Is there a firewall being installed or activated?

**Comment by jamesstringerparsec** [comment]
I have no used IBM's cloud platform nor run this script on it.  I have no idea.
