### ISSUE TITLE
Alibaba Elastic GPU

### ISSUE THREAD

**Issue by rzdev** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#31]
Hi, thanks for this awesome script, been gaming on Google Cloud without any problem. Just wondering are there any plans to support Alibaba GPU?

References:  
https://www.alibabacloud.com/product/gpu 
https://www.alibabacloud.com/help/doc-detail/60149.htm

**Comment by jamesstringerparsec** [comment]
Please read the readme QA section
