### ISSUE TITLE
ERROR CODE 6023

### ISSUE THREAD

**Issue by ronaldrotte** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#34]
Well I came to your code through a youtube video and when I copied the steps of the youtuber, I ended up getting different results as compared to him.On his Azure cloud pc everything worked fine but on mine it says error code 6023 when I try to connect to cloud pc ! Help on this issue will be appreciated !

**Comment by jamesstringerparsec** [comment]
This is a Parsec issue, not an issue with this script.  You need to Google "Parsec 6023".

**Comment by ronaldrotte** [comment]
![correct](https://user-images.githubusercontent.com/64624259/80825879-dc2b4a00-8bfe-11ea-8850-0143981e568e.png)

Is this all the things I should get if I executed the script correctly ? I am asking this because I didn't got all of the shown things ! 

Also is the script responsible to ask to enable auto log in ? when I pasted the code it opened two windows and one of the windows asked me this question !

**Comment by jamesstringerparsec** [comment]
No, the script has changed and removed some things, and the script now asks for your password instead of doing the "auto logon" step.

**Comment by ronaldrotte** [comment]
woah then I think the script indeed worked correctly ! and thank you for your fast replies ! ! And yes it asked for my credentials as well which I entered correctly, hence I am sure that it is indeed a PARSEC ONLY problem ! AGAIN thank you very much !
