### ISSUE TITLE
auto login folder 

### ISSUE THREAD

**Issue by imran254512** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#38]
hi
when the process will complete I will not get persec auto login folder in desktop what can i do please help

**Comment by jamesstringerparsec** [comment]
The need for an auto login folder is out dated.  You no longer need this.

**Comment by nateberkopec** [comment]
The only thing I don't like about the new process is that it's not clear what to put in the login dialog box that pops up, particularly the username. I tried "Administrator", and it didn't work.
