### ISSUE TITLE
Why does this install VNC?

### ISSUE THREAD

**Issue by anaisbetts** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#5]
What does this use VNC for? It seems unneeded, and having a hard-coded password seems Particularly Bad

**Comment by toddmerrill** [comment]
Without explanation too.  I think it's safe to assume it's to hack into your server with root access.

**Comment by sopel** [comment]
See [Using The Parsec AMI On Amazon](https://support.parsecgaming.com/hc/en-us/articles/115003642812-Using-The-Parsec-AMI-On-Amazon):

> BACKUP - USE VNC
The Parsec AMI comes pre-installed with VNC for troubleshooting purposes. VNC runs with elevated privileges and is able to function in certain situations where Parsec cannot. VNC uses port TCP 5900, and has a default password of 4ubg9sde. **Make sure to only allow connections to port 5900 from your IP, and change the default password immediately on login**  — please do these two things. It’s a major security risk if you don’t. _[emphasis mine]_

I agree that this important security info should also be included in the README here.

**Comment by anaisbetts** [comment]
Since all of the machines are server SKU, it seems like it'd be way better to enable RDP instead? Azure already does this by default, and it's way more sane than VNC

**Comment by jamesstringerparsec** [comment]
> Without explanation too. I think it's safe to assume it's to hack into your server with root access.

You're out of your mind.

The reason I enable VNC is because you need a secondary method for accessing the VM that doesn't protect the desktop.  RDP protects the desktop and thus breaks Parsec.

You can change the password - you can also just not allow TCP port 5900 in the firewall.

**Comment by toddmerrill** [comment]
Hi James.  Sorry that my tone upset you, but consider.  You have a script that runs EC2 instance with full rights on other people's machines.  It opens a connection that allows anyone complete access to the instance.  Any reasonable person should make the assumption I did.  Yes, you didn't intend to take over peoples machines, but anyone coming across this project can write a trivially simple scanner that can.  The internet's a dangerous place and we need to make it as secure as possible.  I think it's great you threw this script together, but one string of break-in attacks and we won't be able to use any more cool scripts like yours.  Cheers.

**Comment by jamesstringerparsec** [comment]
> Hi James. Sorry that my tone upset you, but consider. You have a script that runs EC2 instance with full rights on other people's machines. It opens a connection that allows anyone complete access to the instance. Any reasonable person should make the assumption I did. Yes, you didn't intend to take over peoples machines, but anyone coming across this project can write a trivially simple scanner that can. The internet's a dangerous place and we need to make it as secure as possible. I think it's great you threw this script together, but one string of break-in attacks and we won't be able to use any more cool scripts like yours. Cheers.

VNC is not exposed to the internet unless you specificaly make changes to your AWS/Azure security group in order to allow port 5900 inbound.    By Default, VNC has no capability to connect to the internet.

I will document the install of VNC in the readme, along with its TCP port as well as a reminder to change the password and lock TCP 5900 down to a single IP address.

**Comment by toddmerrill** [comment]
Hi James.  You are correct.  I misread your statement about the firewall ::shame::  I saw your statement 'you can also just not allow TCP port 5900' and didn't see the default setting part.  Thanks for the script and sorry about the unjustified freak-out.

**Comment by jamesstringerparsec** [comment]
A warning has been added to the readme.md
