### ISSUE TITLE
DuplicateOutput problem with Windows Server 2019

### ISSUE THREAD

**Issue by NitriKx** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#6]
I've seen a comment about Windows 2019 Server that says "I do not actually recommend Server 2019, seems to break stuff...investigating.". 
What is it exactly? I may help with it.

**Comment by NitriKx** [comment]
Ok I've done the installation on a fresh Windows 2019 AMI and the problems seems to be located when Parsec try to "Duplicate": 

![Screenshot 2019-09-21 13 38 53](https://user-images.githubusercontent.com/1231438/65372816-2e71b900-dc75-11e9-9e09-9db922a68464.png)

**Comment by jamesstringerparsec** [comment]
From memory - 

- Autologon fails to work properly so the desktop doesn't unlock on startup.
- ViGEm controller drivers don't work on Server 2019.

Can you confirm these two issues?

**Comment by NitriKx** [comment]
I’ve not tried the auto login neither ViGEm.
The streaming is not working probably because one of the process is not running with LOCAL_SYSTEM permission scope

**Comment by Carl-Gustaf** [comment]
I'm keen on getting parsec to work on 2019 server too, is there anything I can test?

**Comment by jamesstringerparsec** [comment]
Is there any practical need to have this compatible with Server 2019 other than "it would be cool" ? Right now there are some bugs with inputs with Parsec and Server 2019, so even if these scripts will be made to work correctly, there will still be input issues.  From my understanding there are not many functional differences between Server 2019 and 2016 as far as cloud desktops go.

**Comment by Carl-Gustaf** [comment]
Thank you for your blazing fast answer! No there are no reasons why besides the fact that my machine is a server 2019, I'll just have to get a 2016 instance.

**Comment by wagnerbarretto** [comment]
> Is there any practical need to have this compatible with Server 2019 other than "it would be cool" ? Right now there are some bugs with inputs with Parsec and Server 2019, so even if these scripts will be made to work correctly, there will still be input issues. From my understanding there are not many functional differences between Server 2019 and 2016 as far as cloud desktops go.

Right now one of the main benefits of server 2019 would be to install the Xbox game pass PC app. I'm not 100% sure that it runs on server 2019 because I never tested, but in theory it would since the app requires Windows version 1903. I know for sure that the app does not install on server 2016.

**Comment by jamesstringerparsec** [comment]
@wagnerbarretto You should boot up a server 2019 instance and see if it does legitimately install.

**Comment by htappen** [comment]
Wagner, did you ever figure out how to get Xbox Game Pass installed? I've tried copying packages from a valid Windows 10 instance over to no success

**Comment by wagnerbarretto** [comment]
@htappen not yet. I'm testing on AWS and the only Windows 1903 images they provide are core versions, which are versions without UI. So in order to make it work it would be necessary to either install the windows UI components on a core image (I think it is called Desktop Experience or something like that), or take an AWS full image and upgrade it all the way to version 1903. From what I saw, both things are not very straight forward to do and I didn't find the free time to try them yet.

There is another option that is trying to run Windows 10 on EC2 like described [here](https://gist.github.com/peterforgacs/abebc777fcd6f4b67c07b2283cd31777). This would even bring the costs down since we would be paying linux prices.

Of course all this problems are AWS related. I didn't research other cloud providers and I also don't have access to bare metal hardware to test.

**Comment by htappen** [comment]
Google Cloud also doesn't offer Win10 images, and Server Core as far as I can tell has no supported way to add in the stuff necessary for Windows Store. So, I think Server 2016 is the best bet until 2022 :)

I wonder if Win10 on Azure might be easy, too? http://www.ayushrathi.com/creating-a-win-10-virtual-machine-azure-portal/

**Comment by Nun-z** [comment]
Hi, I was able to install Xbox Games Pass on Windows Server 2016.

Partial guide: https://www.reddit.com/r/cloudygamer/comments/e4rihi/guide_to_installing_microsoft_store_on_paperspace/?utm_medium=android_app&utm_source=share

**Comment by jamesstringerparsec** [comment]
Cloud prep tool now supports 2019, closing this
