### ISSUE TITLE
Access is disabled for devcon.exe

### ISSUE THREAD

**Issue by rshii** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#8]
Thanks for this awesome tool! Running the script today I can't download the resource devcon.exe from https://s3.amazonaws.com/parsec-files-ami-setup/Devcon/devcon.exe
Failing on line 106 in PostInstall.ps1

**Comment by MInner** [comment]
+1. Attempting to access this file via a browser yields the following error: "All access to this object has been disabled".

**Comment by jamesstringerparsec** [comment]
My credit card expired on my S3 account, sorry guys.  🤷‍♂ It should be fixed soon

**Comment by MInner** [comment]
Thank you, awesome, works now. I am still genuinely pleasantly amazed by the fact that people at parsec do not charge users for such an amazing piece of software!
