### ISSUE TITLE
Enhancement - Install Microsoft Store with Xbox Identity Provider

### ISSUE THREAD

**Issue by Nun-z** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#9]
In order to use Xbox Games Pass with Windows Server 2016 or 2019, the Microsoft Store must be installed alongside Xbox Identity Provider.  

This can be done using the following solutions: https://github.com/Nun-z/LTSB-Add-MicrosoftStore for Server 2016 and https://github.com/Nun-z/LTSC-Add-MicrosoftStore for Server 2019.

Note: this is only tested working for Server 2016.

**Comment by jamesstringerparsec** [comment]
I'm not prepared to include this into this script, because it seems super hacky and probably outside the terms of the license agreement of the software.

**Comment by Nun-z** [comment]
You're not wrong.  I'll add it to my fork of this when I have time.
